### ISSUE TITLE
InferenceLoop should raise an error when predictor does not have predict method

### ISSUE THREAD

**Issue by mottodora** [pfnet-research/chainer-chemistry#106]
related to #103 
I feel it is kind to check whether predictor has 'predict' method.
Like `if callable(getattr(predictor_, 'predict', None))`

**Comment by mottodora** [comment]
I think it is kind to raise error when `predictor` does not have `predict` method.

**Comment by delta2323** [comment]
I agree. Then how about changing the issue title to "`InferenceLoop` should raise an error when `predictor` does not have `predict` method"?

**Comment by mottodora** [comment]
OK and I will make a PR.

**Comment by delta2323** [comment]
Closed, as the Tox21 example does not have `InferenceLoop` any longer.
