### ISSUE TITLE
Do not import BalancedSerialIterator conditionally in the Tox21 example.

### ISSUE THREAD

**Issue by delta2323** [pfnet-research/chainer-chemistry#121]
`BalancedSerialIterator` is a feature introduced in v0.2.0. Before we the release of v0.2.0, we need to check its availability in the Tox21 example to work it with the latest release (i.e. v0.1.0). Now that v0.2.0 has been released, we need not to do so.

**Comment by corochann** [comment]
Same applies for `ROCAUCEvaluator`, and note that `RSGCN` availability is not checked from the beggining of merge.
