### ISSUE TITLE
Remove redundant import of matplot lib from the Tox21 and the QM9 example.

### ISSUE THREAD

**Issue by delta2323** [pfnet-research/chainer-chemistry#122]
Import of matplotlib in the examples are redundant as it is not used. So we should remove it. But some people reports they cause errors without it. So let me know if you encounter similar phenomena.

**Comment by mihaimorariu** [comment]
I tested both examples with Python 2.7 and 3.6 (under Arch Linux). No problems encountered.
matplotlib version: 2.2.2

**Comment by delta2323** [comment]
Thank you for investigation. I sent a PR that fixes it.

**Comment by delta2323** [comment]
Fixed via #148
