### ISSUE TITLE
segmentation fault in example

### ISSUE THREAD

**Issue by fullswing** [pfnet-research/chainer-chemistry#138]
I have followed commands introduced in README in order to run examples, but it failed in segmentation fault.

Here is my environment.
chainer version:3.5.0
OS:mac OS High Sierra version 10.13.4
Anaconda version:4.5.0

I created chainer-env via Anaconda following commands below.
```
$ conda create -c rdkit -n chainer-env rdkit
$ conda activate chainer-env
$ pip install chainer
$ conda install scikit-learn, pandas, tqdm
$ git clone https://github.com/pfnet-research/chainer-chemistry.git
$ pip install -e chainer-chemistry
```
Next I tried to run the example introduced in README.
But unfortunately these commands ended up with segmentation fault.
```
$ cd chainer-chemistry/examples/tox21
$ python train_tox21.py --method=nfp  --gpu=0 
zsh: segmentation fault  python train_tox21.py --method=nfp --gpu=0
```

I investigated this case and found the following might be the cause of this problem.
```
$ python
>>> import chainer
>>> import rdkit # this works
$ python
>>> import rdkit
>>> import chainer
segmentation fault
```
Say, `import rdkit` after `import chainer` works but the opposite does not.

**Comment by n-yoshikawa** [comment]
I had the same problem on macOS (High Sierra 10.13.4, conda 4.4.10, python 3.6.4, rdkit 2017.09.3.0). This may be related to [rdkit/rdkit#1617](https://github.com/rdkit/rdkit/issues/1617). I'm looking for a workaround.

**Comment by fullswing** [comment]
Your solution worked in my environment.
Thank you!

**Comment by delta2323** [comment]
@fullswing Can I close this PR as it is not a problem of Chainer Chemistry?

**Comment by fullswing** [comment]
Sorry, I will.
