### ISSUE TITLE
Remove inference_tox21.py and relevant code from the Tox21 example.

### ISSUE THREAD

**Issue by delta2323** [pfnet-research/chainer-chemistry#161]
Now we have `predict_tox21_with_classifier.py` for inference that does almost same things as `inference_tox21.py` does with official APIs. It is confusing to provide two scripts for one objective. So we should remove the latter.

**Comment by corochann** [comment]
When do you think is the best timing to remove?

**Comment by delta2323** [comment]
Solved by #184
