### ISSUE TITLE
fail to import rdkit.Chem.rdmolops

### ISSUE THREAD

**Issue by tek1031** [pfnet-research/chainer-chemistry#167]
I failed to import rdkit.Chem.rdmolops.
You can reproduce this issue by following step.

```
conda -n create test python=3.6 anaconda
source activate test
pip install chainer-chemistry
conda install -c rdkit rdkit
python
from rdkit.Chem.rdmolops import *
```
Error message is
`module compiled against API version 0xb but this version of numpy is 0xa`

I avoid this error by upgrading numpy,  just executing `pip install numpy --upgrade`

**Comment by mottodora** [comment]
Do we need to specify the version of numpy?

**Comment by tek1031** [comment]
At least, numpy 1.12.1 doesn't work.

**Comment by corochann** [comment]
Issue resolves with
`pip install numpy --upgrade`

So maybe we can write it to the document for trouble shooting?

**Comment by corochann** [comment]
or simply close without modification since this is not inside the problem of chainer chemistry???

**Comment by delta2323** [comment]
I would suggest to write in the README that we test Chainer Chemistry with the latest NumPy.

**Comment by corochann** [comment]
We fixed recommended rdkit version.
