### ISSUE TITLE
Support PDBBind dataset

### ISSUE THREAD

**Issue by mottodora** [pfnet-research/chainer-chemistry#212]
In MoleculeNet dataset

**Comment by s-fukushima-a42** [comment]
I'd like to try affinity prediction with the pdbbind dataset, but how do I load datasets?

```
Please choose from ['bace_Class', 'bace_pIC50', 'bbbp', 'chembl', 'clearance', 'clintox', 'delaney', 'HIV', 'hopv', 'kaggle', 'lipo', 'muv', 'nci', 'pcba', 'ppb', 'qm7', 'qm8', 'qm9', 'SAMPL', 'sider', 'tox21', 'toxcast']
```

**Comment by mottodora** [comment]
Sorry for late reply. We are implementing PDBBind dataset loader now. 
Could you please wait a minute?

**Comment by s-fukushima-a42** [comment]
Thank you for your response.
I am not hurrying you.
Please, implement in sequence. :)

**Comment by mottodora** [comment]
Sorry for late.
We support PDBBind dataset. #255

**Comment by corochann** [comment]
Can we close the issue?
