### ISSUE TITLE
Why does evaluation of tox21 models use not test dataset but validation dataset?

### ISSUE THREAD

**Issue by tamuhey** [pfnet-research/chainer-chemistry#335]
Thanks for this cool library!

The [tox21 model](https://github.com/pfnet-research/chainer-chemistry/tree/master/examples/tox21) is trained with "train" and "val" dataset defined in the following line:

https://github.com/pfnet-research/chainer-chemistry/blob/bc90b1b0e5019e7676e4973965f87f09b4987d2c/examples/tox21/data.py#L81

And the model is evaluated with "val" dataset, not "test", as follows:

https://github.com/pfnet-research/chainer-chemistry/blob/bc90b1b0e5019e7676e4973965f87f09b4987d2c/examples/tox21/predict_tox21_with_classifier.py#L50

Why "test" dataset is not used?

**Comment by corochann** [comment]
Thank you for your comment.
I remember `test` data actually does not contain "label" information. I guess this is tox21 contest dataset and `test` dataset is really a "test" dataset and its label is blind.

So we used validation data for checking model's accuracy in the example.

**Comment by tamuhey** [comment]
Thanks for reply!

Test label is here:
http://bioinf.jku.at/research/DeepTox/tox21.html

**Comment by corochann** [comment]
Thank you for info.
You can also refer `molnet` dataset, which also contains tox21 data.
Sorry I did not check the test label is contained or not in molnet.
