### ISSUE TITLE
How to use weavenet?

### ISSUE THREAD

**Issue by soerendip** [pfnet-research/chainer-chemistry#369]
Hi,

I am looking for an example of how to use the models implemented in chainer_chemistry. The documentation is not too detailed.

Cheers

**Comment by corochann** [comment]
Please refer `examples` directory for typical usage.
 - https://github.com/pfnet-research/chainer-chemistry/tree/master/examples
QM9 is for regression task and tox21 is for classification task.

If you have more concrete question where you want to know, please ask here.

**Comment by corochann** [comment]
Can we close the issue? @soerendip
