### ISSUE TITLE
numpy seems to be missing in install_requires

### ISSUE THREAD

**Issue by yurivict** [pfnet-research/chainer-chemistry#375]
https://github.com/pfnet-research/chainer-chemistry/blob/master/setup.py#L7

The project does import numpy.

**Comment by corochann** [comment]
Thank you for suggestion.
Currently numpy dependency is included in chainer repo, so it is automatically installed.

 - https://github.com/chainer/chainer/blob/master/setup.py#L33

**Comment by corochann** [comment]
Can we close the issue? @yurivict
