### ISSUE TITLE
ImportError: cannot import name 'set_up_predictor' 

### ISSUE THREAD

**Issue by fr-takumaurata** [pfnet-research/chainer-chemistry#384]
I'm struggling with import error.
I just set up following tutorial. Is there anyone help me?
```
from chainer_chemistry.models.prediction import set_up_predictor
ImportError: cannot import name 'set_up_predictor' from 'chainer_chemistry.models.prediction' (*/Applications/anaconda3/lib/python3.7/site-packages/chainer_chemistry/models/prediction/__init__.py)
```

**Comment by corochann** [comment]
`set_up_predictor` is implemented in master branch, but not in released library.

I guess you install chainer-chemistry via pip `pip install chainer-chemistry` and trying examples in this master branch??


Please install chainer-chemistry master branch as follows:

```
# uninstall chainer-chemistry via pip
$ pip uninstall chainer-chemistry

# install master branch
$ git clone https://github.com/pfnet-research/chainer-chemistry.git
$ pip install -e chainer-chemistry
```

**Comment by fr-takumaurata** [comment]
Thank you for quick response! I fixed it following your advice.
