### ISSUE TITLE
QM9 with coordinates

### ISSUE THREAD

**Issue by nshervt** [pfnet-research/chainer-chemistry#404]
When using get_qm9 function, I was wondering 

1. if it is possible to load coordinate data that is provided in the original QM9 publication using Chainer Chemistry. 

2. Also, it seems that the SMILES in the original paper are slightly different from the ones that are loaded here. For instance, there is no indication of chirality in the SMILES that are loaded using Chainer Chemistry. Is there a way to load those information as well?

Thanks!

**Comment by corochann** [comment]
I'm sorry for the late reply...

1. loading coordinates should be nice feature to have, but currently it is not supported. Sorry...

2. Preprocessed data which stores smiles and labels is located in this place: `~/.chainer/dataset/pfnet/chainer/qm9/qm9.csv`. Please refer this if you want to do some advanced handling. Current chainer-chemistry (and almost all graph convolution neural network) cannot handle chirality information and we are skipping to handle it for now...

**Comment by nshervt** [comment]
Thanks!
