### ISSUE TITLE
Example command "python train_qm9.py -g 0" get "main/accuracy" over 100score...☹️

### ISSUE THREAD

**Issue by inoue0426** [pfnet-research/chainer-chemistry#73]
## Enviroment 
Ubuntu 16.04.3
Python 3.5.4
chainer (3.1.0)
chainer-chemistry (0.1.0)
cupy (2.1.0.1)

"main/accuracy" and "validation/main/accuracy" get over 100 score...☹️

<img width="1421" alt="2017-12-30 22 05 09" src="https://user-images.githubusercontent.com/8393063/34454441-ed115d78-edae-11e7-95a4-a601f81e502d.png">

And, I tried the command "python train_qm9.py --method=nfp  --gpu=0 ", but the score get over 100 score...☹️

<img width="1431" alt="2017-12-30 22 14 00" src="https://user-images.githubusercontent.com/8393063/34454499-2ce17554-edb0-11e7-8512-289afe00a832.png">

Please, teach me.

**Comment by corochann** [comment]
We are sorry for few documentation.
qm9 example is regression task. "loss" is taken as mean squared error of standardized data, and "accuracy" represents mean absolute error of non-standardized data.
Therefore, even it is written as "accuracy", it is actually not the classification accuracy.

We should consider update the documentation or example itself.

**Comment by corochann** [comment]
http://chainer-chemistry.readthedocs.io/en/latest/tutorial.html

Please also refer this tutorial for detail explanation.

**Comment by inoue0426** [comment]
Oh, I see 😮
I skipped reading...😓
Thank you !!
