### ISSUE TITLE
RSGCN TODO list

### ISSUE THREAD

**Issue by corochann** [pfnet-research/chainer-chemistry#95]
Remaining task after 
https://github.com/pfnet-research/chainer-chemistry/pull/89

[Required]
 - Add test code
 Both pytest and example.sh code
   -- Test `predict` code of tox21
 - Add the network and paper citation in README

[Nice to have]
 - Residual connection option:
Original paper experiments with/with out residual connection in appendix.
So option kwargs can be added on network to add residual connection or not.
 - Add network in QM9 example as well.
 - Support sparce matmul.
They claim calculation can be faster with sparce matrix.
https://github.com/tkipf/pygcn/blob/master/pygcn/layers.py#L9

**Comment by corochann** [comment]
Also from #89

When I test the model performance with ROC AUC Evaluator (https://github.com/pfnet-research/chainer-chemistry/pull/62), I found the following.

1. It is better to add `softmax` function in default readout func.
The model train progress becomes much stable (somehow) with adding softmax function in readout as follows.

```
def _readout_sum(x):
    h = functions.softmax(x, axis=2)  # softmax along channel axis
    y = functions.sum(h, axis=1)  # sum along node axis
    return y
```

2. Support a case when `readout` is a class of `Link`.
Currently `readout` args in `__init__` is not registered inside `init_scope`. 
But user may want to pass `Chain` class as `readout`, it becomes more flexible to check if `readout` isinstanceof Link or not and register inside `init_scope` if so.


**It is ok for me to send above PR 1 & 2 by myself after merge this PR at first.** Is it ok for you?

**Comment by delta2323** [comment]
@coochann No problem. How about making issues and assigning youself.

**Comment by corochann** [comment]
[Required] section has done.
